stop-words = "./lemur-stopwords.txt"
prefix = "."

dataset = "data"
corpus = "file.toml"
index = "ejemplo1-metapy-idx"

query-judgements = "./ejemplo1-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
